In [1]:
import numpy as np
M = np.array([[0,4,5,6],[4,0,4,9],[5,4,0,10],[6,9,10,0]])
print("Distance Matrix:")
print(M)

def cluster(point,r):
    c = []
    pts = point.copy()
    for i in pts:
        if M[pts[0]][i] <= 2*r:
            c.append(i)
            point.remove(i)
    t = c.copy()
    while len(t) != 0:
        for i in t:
            t.remove(i)
            for j in point:
                if M[i][j] <= 2*r:
                    c.append(j)
                    t.append(j)
                    point.remove(j)
    return [c,point]

def main(point,r):
    out = []
    pts = point.copy()
    for i in range(len(point)):
        m = cluster(point,r)
        out.append(m[0])
        if len(m[1]) == 0:
            break
    return out

p = [i for i in range(len(M))]
print("")
r = float(input("Input radius: "))
print("")
print("Output:")
print(main(p,r))

Distance Matrix:
[[ 0  4  5  6]
 [ 4  0  4  9]
 [ 5  4  0 10]
 [ 6  9 10  0]]

Input radius: 1

Output:
[[0], [1], [2], [3]]


In [19]:
import numpy as np
N = np.array([[0,4,5,6,9],[4,0,4,9,15],[5,4,0,10,20],[6,9,10,0,13],[9,15,20,13,0]])
print("Distance Matrix:")
print(N)

def cluster(point,r):
    c = []
    pts = point.copy()
    for i in pts:
        if N[pts[0]][i] <= 2*r:
            c.append(i)
            point.remove(i)
    t = c.copy()
    while len(t) != 0:
        for i in t:
            t.remove(i)
            for j in point:
                if N[i][j] <= 2*r:
                    c.append(j)
                    t.append(j)
                    point.remove(j)
    return [c,point]

def main(point,r):
    out = []
    pts = point.copy()
    for i in range(len(point)):
        m = cluster(point,r)
        out.append(m[0])
        print(out)
        if len(m[1]) == 0:
            break
    return out

h = [i for i in range(len(N))]
print("")
k = float(input("Input radius: "))
print("")
print("Output:")
print(main(h,k))

Distance Matrix:
[[ 0  4  5  6  9]
 [ 4  0  4  9 15]
 [ 5  4  0 10 20]
 [ 6  9 10  0 13]
 [ 9 15 20 13  0]]


Output:
[[0]]
[[0], [1]]
[[0], [1], [2]]
[[0], [1], [2], [3]]
[[0], [1], [2], [3], [4]]
[[0], [1], [2], [3], [4]]
